services:
  - type: web
    name: symfony-app
    runtime: docker
    env: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      chmod -R 777 var
      php bin/console cache:clear
      php-fpm
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        value: votre_secret_app  # Utilisez une valeur sécurisée
      - key: DATABASE_URL
        value: mysql://root:03302joachin@containers-us-west-99.railway.app:3306/travel?serverVersion=8.0&charset=utf8mb4
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,REMOTE_ADDR"
      - key: TRUSTED_HOSTS
        value: "^.*$"  # À restreindre sur les environnements de production réels

  - type: database
    name: symfony-db
    engine: mysql
    version: 8.0
    plan: free
    databaseName: travel
    user: root
    password: 03302joachin
